import { diffrences } from "@/data";
import Button from "@/shared/ui/Button";
import Footer from "@/shared/ui/Footer";
import Header from "@/shared/ui/Header";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";



export default function Home() {
const [content, setContent] = useState("нажми на кнопку")

console.log("App component Render")

function handlClick(type){
  console.log("button clicked", type);
  setContent(type)
}

  return (
    <>
      <Head>
        <title>computer club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <section className="phti">
            <div className="container">
             <Header/>

             <div className="banner">
               <button className="btn">
                <Link href="#" className="lnk3">
                забронировать ПК
                </Link>
               </button>

             </div>
            </div>
          </section>

           <section className="phti">
            <div className="container">
              <div className="game_bnr">
              <div className="bnr_top">
                <div className="bnr_icon">
                  <img src="./img/fire.png" alt="" />
                </div>
                  
                  <p className="txt2">
                    сыграй в <span className="gr">любую</span>   <br />
                     из этих игр в нашем <span className="f">клубе</span>
                  </p>
              </div>

              <div className="bnr_grid">
                <div className="bnr_itm">
                  <img src="./img/itm1.png" alt="" />
                </div>

                <div className="bnr_itm">
                  <img src="./img/itm2.png" alt="" />
                </div>

                <div className="bnr_itm">
                  <img src="./img/itm3.png" alt="" />
                </div>

                <div className="bnr_itm">
                  <img src="./img/itm4.png" alt="" />
                </div>

                <div className="bnr_itm">
                  <img src="./img/itm5.png" alt="" />
                </div>

                <div className="bnr_itm">
                  <img src="./img/itm6.png" alt="" />
                </div>
                
                <div className="bnr_itm">
                  <img src="./img/itm7.png" alt="" />
                </div>

              </div>
                 
                 <button className="btn2">
                <div className="pc_icon">
                  <img src="./img/PC.png" alt="" />
                </div>

                  <Link href="#" className="lnk4">
                  забронировать ПК
                  </Link>
                 </button>
              </div>

            </div>
            </section> 

            <section className="phti">
              <div className="container">
                <div className="establishments_block">
                   <p className="txt3">
                     о заведении
                   </p>
                   
                   <div className="establishments_grid">
                     <div className="elm">
                        <div className="elm_icn">
                          <img src="./est_pht/Glyph.png" alt="" />
                        </div>

                          <p className="txt4">
                            Современное круглосуточное киберспортивное <br />
                            пространство с 57 пк, 4 зонами, 3 VIP-комнатами <br />
                            и собственным меню и авторскими коктейлями!
                          </p>
                     </div>

                     <div className="elm">
                        <div className="elm_icn">
                          <img src="./est_pht/gme.png" alt="" />
                        </div>

                          <p className="txt4">
                            <strong>Адрес:</strong>Ломонсовский проспект, 29к3, Москва; <br />
                            <strong>Телефон:</strong>+7 (999) 099-43-33 <br />
                            <strong>Время работы:</strong>круглосуточно
                          </p>
                     </div>

                     <div className="elm">
                        <p className="txt5">
                          <span>Крутые</span> <br />
                           девайсы
                        </p>

                          <p className="txt6">
                            Играй на современном железе, слушай в топовых <br />
                            наушниках, кликай на механической клавиатуре. <br />
                            Будь уверен, наши девайсы дают раскрыть весь <br />
                            твой игровой скилл на максимум. 
                          </p> 
                     </div>

                     <div className="elm_photo">
                      <img src="./est_pht/pht.png" alt="" />
                     </div>
                   </div>

                </div>
              </div>
            </section>

            <section className="phti">
              <div className="container">
                <div className="playstation_block">
                 <div className="playstation_itm">

                   <div className="playstation_left">
                      <img src="./est_pht/ps1.png" alt="" />
                      <div className="ps2">
                        <img src="./est_pht/ps2.png" alt="" />
                      </div>
                   </div>
                     
                     <div className="playstation_rigth">
                       <p className="txt7">
                        играй на <br />
                        <span>playstation 5</span>
                       </p>
                     </div>
                 </div>

                </div>
              </div>
            </section>

            <section className="phti">
              <div className="container">
                <div className="photo_block">
                 <div className="photo_top">
                  <div className="camera_icon">
                    <img src="./est_pht/camera.png" alt="" />
                  </div>

                  <p className="txt8">
                    Фотки с нашего клуба
                  </p>
                 </div>

                 <div className="photo_flex">
                  <div className="pohoto_left">
                     <div className="pht1">
                      <img src="./est_pht/pht1.png" alt="" />
                     </div>

                     <div className="pht1">
                      <img src="./est_pht/pht2.png" alt="" />
                     </div>
                  </div>

                  <div className="pht_centr">
                    <img src="./est_pht/pht3.png" alt="" />
                  </div>

                   <div className="pohoto_left">
                     <div className="pht1">
                      <img src="./est_pht/pht1.png" alt="" />
                     </div>

                     <div className="pht1">
                      <img src="./est_pht/pht2.png" alt="" />
                     </div>
                  </div>
                 </div>
                </div>

              </div>
            </section>

            <section className="bp">
              <div className="container">
                <div className="btn_block">
                  <div className="btn_top">
                  <Button onClick={() => handlClick("way")}>Подход</Button>
                  <Button onClick={() => handlClick("easy")}>Доступность</Button>
                  <Button onClick={() => handlClick("programm")}>Концентрация</Button>
                  </div>

                  <div>
                    <p className="txt20">{diffrences[content]}</p>
                  </div>
                </div>
              </div>
            </section>

            <section className="phti">
              <div className="container">
                <div className="gasu_blockk">
                  <div className="gasu_top">
                    <div className="lgo">
                      <img src="./img/hdr_logo.png" alt="" />
                    </div>

                    <p className="txt9">
                      наши преимущества
                    </p>
                  </div>
                    
                    <div className="gasu_flex">
                      <div className="gasu_itm">
                        <div className="gasu_pht">
                          <img src="./img/vdcrt.png" alt="" />
                        </div>

                        <div className="gasu_bottom">
                          <p className="txt10">Видеокарты</p>
                          <p className="txt11">RTX 3070, RX 6900 XT</p>
                        </div>
                      </div>

                      <div className="gasu_itm">
                        <div className="gasu_pht">
                          <img src="./img/disp.png" alt="" />
                        </div>

                        <div className="gasu_bottom">
                          <p className="txt10">Мониторы</p>
                          <p className="txt11">240 HZ, 240 HZ FHD</p>
                        </div>
                      </div>
                    </div>

                </div>
              </div>
            </section>

            <section className="phti">
              <div className="container">
                <div className="gs_b">
                   <div className="gs_grid">
                    <div className="gs_itm">
                      <div className="gs_top">
                        <img src="./img/gs1.png" alt="" />
                      </div>

                       <div className="gs_btm">
                         <p className="txt12">Best Devices</p>
                         <p className="txt13">Best Devices</p>
                       </div>
                    </div>


                    <div className="gs_itm">
                      <div className="gs_top">
                        <img src="./img/gs1.png" alt="" />
                      </div>

                       <div className="gs_btm">
                         <p className="txt12">Best Devices</p>
                         <p className="txt13">Best Devices</p>
                       </div>
                    </div>


                    <div className="gs_itm">
                      <div className="gs_top">
                        <img src="./img/gs1.png" alt="" />
                      </div>

                       <div className="gs_btm">
                         <p className="txt12">Best Devices</p>
                         <p className="txt13">Best Devices</p>
                       </div>
                    </div>

                    <div className="gs_itm">
                      <div className="gs_top">
                        <img src="./img/gs1.png" alt="" />
                      </div>

                       <div className="gs_btm">
                         <p className="txt12">Best Devices</p>
                         <p className="txt13">Best Devices</p>
                       </div>
                    </div>
                   </div>

                </div>
              </div>
            </section>

            <section className="xn">
              <div className="container">
                <div className="game_zona_block">
                      <div className="game_banner">
                         <div className="game_lm">
                         <div>
                           <p className="txt15">Зона</p>

                          <p className="txt16">
                            standart
                          </p>
                         </div>

                          <div className="game_grid">
                            <div className="gm_tm">
                              <p className="txt17">
                                24 ПК с мощным железом
                              </p>

                              <div className="gm_r">
                                <img src="./img/gm_r2.png" alt="" />
                              </div>
                            </div>

                              <div className="gm_tm">
                              <p className="txt17">
                                27” Мониторы  <br />
                                с частотой 144 гц
                              </p>

                              <div className="gm_r">
                                <img src="./img/gm_3.png" alt="" />
                              </div>
                            </div>

                              <div className="gm_tm">
                              <p className="txt17">
                               Механические <br />
                                клавиатуры на Blue свитчах
                              </p>

                              <div className="gm_r_2">
                                <img src="./img/cl.png" alt="" />
                              </div>
                            </div>
                          </div>
                         </div>
                      </div>
                   

                </div>
              </div>
            </section>

            <section className="prr">
              <div className="container">
                <div className="prm_blck">
                   <div className="premium_br">
                    <div className="prm_left">
                      <div className="prm_top">
                       <div className="cocktail_icn">
                        <img src="./img/cocktail.png" alt="" />
                       </div>

                        <p className="txt18">
                          premium бар
                        </p>
                      </div>

                      <p className="txt19">
                        Наше заведение подарит каждому гостю приятную атмосферу и <br />
                        гастрономическое удовольствие. Здесь вы найдёте все для отдыха: аппетитный <br />
                        выбор пиццы, салатов, пасты, десертов и других блюд никого не оставит <br />
                        равнодушным. Широкий ассортимент напитков не только утолит жажду, но и <br />
                        оставит свежее послевкусие, за которым захочется вернуться ещё раз
                      </p>

                      <button className="btn3">
                        <div className="pc_icon">
                          <img src="./img/PC.png" alt="" />
                        </div>
                           <Link href="/Par" className="lnk5">
                           забронировать ПК
                           </Link>
                      </button>
                    </div>

                    <div className="prm_ri">
                      <img src="./img/lfttt.png" alt="" />
                    </div>
                   </div>
                </div>
              </div>
            </section>

            <section className="vntb">
              <div className="container">
                <div className="events_block">
                  <div className="evnt_lm">
                    <div className="vnt_left">
                      <p className="txt21">
                        наши события
                      </p>

                      <p className="txt22">Погрузись с нами в киберспортивный мир!</p>

                      <button className="btn4">
                        <div className="clndr">
                          <img src="./img/calendar.png" alt="" />
                        </div>
                         
                        <Link href="#" className="lnk6">
                        Все события
                        </Link>
                      </button>
                    </div>

                    
                    <div className="card_lft">

                                                <div className="card">
  {/* <!-- Сама картинка --> */}
  <img src="./img/usr.png" alt="Background" className="card__img"/>
  
  {/* <!-- Тёмный оверлей для читаемости текста --> */}
  <div className="card__overlay"></div>
  
  {/* <!-- Контент карточки --> */}
  <div className="card__content">
    <div className="card__badge">6 мая</div>
    
    <div className="card__bottom">
      <div className="card__text">
        <h3 className="card__title">«COME BACK» компьютерных салонов</h3>
        <p className="card__description">Управляющий “GOSU” выступил экспертом в Московской газете</p>
      </div>
      <button className="card__btn">
       <Link href="#">
        <img src="./img/arrw_r.png" alt="" />
       </Link>
      </button>
    </div>
  </div>
</div>
                   
                             <div className="card">
  {/* <!-- Сама картинка --> */}
  <img src="./img/zack.png" alt="Background" className="card__img"/>
  
  {/* <!-- Тёмный оверлей для читаемости текста --> */}
  <div className="card__overlay"></div>
  
  {/* <!-- Контент карточки --> */}
  <div className="card__content">
    <div className="card__badge">4 мая</div>
    
    <div className="card__bottom">
      <div className="card__text">
        <h3 className="card__title">Кино в GOSU</h3>
        <p className="card__description">
          Уже совсем скоро в нашем клубе <br />
          пройдет премьера нового Бэтмана
        </p>
      </div>
      <button className="card__btn">
       <Link href="#">
        <img src="./img/arrw_r.png" alt="" />
       </Link>
      </button>
    </div>
  </div>
</div>
                    </div>
                  </div>

                </div>
              </div>
            </section>

            <section className="s_ftr">
              <div className="container">
                <div className="footer_block">
                 
               <Footer/>
                </div>
              </div>
            </section>
        </main>
      </div>
    </>
  );
}
